# Generated by Django 2.1.7 on 2019-05-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
